ALTER TABLE basemap
    ADD COLUMN kind        TEXT NOT NULL DEFAULT 'VECTOR' CHECK (kind IN ('VECTOR', 'RASTER')),
    ADD COLUMN attribution TEXT NOT NULL DEFAULT '',
    ADD COLUMN min_lon     DOUBLE PRECISION,
    ADD COLUMN min_lat     DOUBLE PRECISION,
    ADD COLUMN max_lon     DOUBLE PRECISION,
    ADD COLUMN max_lat     DOUBLE PRECISION;
